In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv("C:\\Users\\krishna\\OneDrive\\Desktop\\Krishna_thesis\\final work\\last final feature matrix.csv")

In [3]:
df.shape

(1116, 19)

In [4]:
df.head()

,avg_si,avg_ti,max_si,max_ti,min_si,min_ti,num_frames,std_si,std_ti,bitrate,width,height,blur_avg,blur_min,blur_max,blur_std,mscn_mean,mscn_std,MOS
0,67.761,11.486,149.348,43.906,0.000,0.000,599,56.717,14.722,39455067,1920,1080,487.469110,0.000000,1433.735087,535.098036,0.0003,0.0226,3.901
1,127.930,8.846,161.529,70.356,92.198,0.007,599,14.157,14.491,20173043,1920,1080,1996.931966,554.755396,10293.566930,1387.619823,0.0009,0.0505,3.940
2,114.687,3.601,139.886,22.136,86.393,0.000,600,13.476,2.806,35246779,1920,1080,754.504431,167.188913,1942.206195,429.063347,0.0006,0.0379,4.158
3,93.078,7.374,110.246,69.041,75.806,0.000,600,9.397,7.805,4884280,1920,1080,2995.681891,2161.869410,3685.894480,598.026164,0.0007,0.0477,4.189
4,82.019,21.565,105.680,39.132,52.316,0.003,599,17.192,12.612,45925284,1920,1080,220.564283,67.775987,415.174225,96.592576,0.0000,0.0188,3.791

In [5]:
df.tail()

,avg_si,avg_ti,max_si,max_ti,min_si,min_ti,num_frames,std_si,std_ti,bitrate,width,height,blur_avg,blur_min,blur_max,blur_std,mscn_mean,mscn_std,MOS
1111,121.056,37.814,138.947,94.695,51.325,0.000,600,19.794,32.814,15206598,1280,720,1758.222462,62.608977,4423.858075,1715.179108,0.0006,0.0448,2.743
1112,14.708,18.318,69.087,63.829,3.315,3.173,600,14.349,11.668,29182761,1280,720,47.318120,1.001485,472.889238,98.796331,0.0005,0.0093,2.794
1113,133.745,43.696,139.519,70.818,106.505,0.000,599,2.871,23.921,22056747,732,720,3056.573031,839.414998,3548.119565,325.420820,0.0003,0.0686,3.783
1114,85.111,27.500,105.933,97.553,17.452,0.009,599,20.121,15.206,21078458,1280,720,651.112704,9.664105,1115.456340,303.075948,0.0007,0.0308,4.335
1115,39.289,22.331,105.462,98.805,8.104,0.127,600,28.327,17.525,20255127,1280,720,315.642088,6.202926,2796.182781,640.202908,0.0006,0.0180,3.776

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116 entries, 0 to 1115
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   avg_si      1116 non-null   float64
 1   avg_ti      1116 non-null   float64
 2   max_si      1116 non-null   float64
 3   max_ti      1116 non-null   float64
 4   min_si      1116 non-null   float64
 5   min_ti      1116 non-null   float64
 6   num_frames  1116 non-null   int64
 7   std_si      1116 non-null   float64
 8   std_ti      1116 non-null   float64
 9   bitrate     1116 non-null   int64
 10  width       1116 non-null   int64
 11  height      1116 non-null   int64
 12  blur_avg    1116 non-null   float64
 13  blur_min    1116 non-null   float64
 14  blur_max    1116 non-null   float64
 15  blur_std    1116 non-null   float64
 16  mscn_mean   1116 non-null   float64
 17  mscn_std    1116 non-null   float64
 18  MOS         1116 non-null   float64
dtypes: float64(15), int64(4)
memory usage: 165.8 KB

In [7]:
df.describe()

,avg_si,avg_ti,max_si,max_ti,min_si,min_ti,num_frames,std_si,std_ti,bitrate,width,height,blur_avg,blur_min,blur_max,blur_std,mscn_mean,mscn_std,MOS
count,1116.000000,1116.000000,1116.000000,1116.000000,1116.000000,1116.000000,1116.000000,1116.000000,1116.000000,1.116000e+03,1116.000000,1116.000000,1116.000000,1116.000000,1116.000000,1116.000000,1116.000000,1116.000000,1116.000000
mean,83.312731,15.637716,113.802804,58.066431,49.183142,1.067750,594.935484,15.856659,9.996179,3.408101e+07,1392.761649,863.177419,1316.558403,465.331672,3955.907154,676.531279,0.000599,0.030851,3.540504
std,43.767873,11.714413,53.856913,33.499498,43.980186,3.548848,35.748265,15.472622,6.751879,5.875463e+07,943.884030,533.980333,3749.766776,1251.296506,12902.676193,2364.803739,0.000522,0.017905,0.652612
min,3.245000,0.003000,3.636000,0.252000,0.000000,0.000000,71.000000,0.002000,0.013000,2.817400e+04,270.000000,320.000000,1.735963,0.000000,3.660910,0.187307,-0.000800,0.001500,1.242000
25%,52.606000,6.466500,78.222250,32.140250,14.834000,0.000000,599.000000,5.330000,4.987750,4.322756e+06,640.000000,480.000000,184.901282,13.052658,398.996903,46.524404,0.000200,0.017900,3.091250
50%,78.401000,13.054500,107.270000,54.737000,40.935000,0.014500,600.000000,11.835000,8.886500,1.335637e+07,1280.000000,720.000000,509.771559,93.937058,1184.344170,175.445426,0.000500,0.027000,3.593500
75%,105.881000,22.503750,141.329000,83.468750,72.119000,0.080000,600.000000,22.109500,13.646500,3.585231e+07,1920.000000,1080.000000,1360.427727,379.093450,3096.760442,540.775740,0.000800,0.041000,4.068000
max,301.909000,73.774000,391.023000,167.639000,301.614000,39.820000,600.000000,135.285000,48.485000,5.183841e+08,4096.000000,3840.000000,106537.750200,21727.000800,280010.814400,58300.394950,0.003600,0.138900,4.677000

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum().sum()

0

In [10]:
df.head()

,avg_si,avg_ti,max_si,max_ti,min_si,min_ti,num_frames,std_si,std_ti,bitrate,width,height,blur_avg,blur_min,blur_max,blur_std,mscn_mean,mscn_std,MOS
0,67.761,11.486,149.348,43.906,0.000,0.000,599,56.717,14.722,39455067,1920,1080,487.469110,0.000000,1433.735087,535.098036,0.0003,0.0226,3.901
1,127.930,8.846,161.529,70.356,92.198,0.007,599,14.157,14.491,20173043,1920,1080,1996.931966,554.755396,10293.566930,1387.619823,0.0009,0.0505,3.940
2,114.687,3.601,139.886,22.136,86.393,0.000,600,13.476,2.806,35246779,1920,1080,754.504431,167.188913,1942.206195,429.063347,0.0006,0.0379,4.158
3,93.078,7.374,110.246,69.041,75.806,0.000,600,9.397,7.805,4884280,1920,1080,2995.681891,2161.869410,3685.894480,598.026164,0.0007,0.0477,4.189
4,82.019,21.565,105.680,39.132,52.316,0.003,599,17.192,12.612,45925284,1920,1080,220.564283,67.775987,415.174225,96.592576,0.0000,0.0188,3.791

In [11]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [12]:
# Import models and utility functions
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as MSE
from sklearn import datasets
  
# Setting SEED for reproducibility
SEED = 42
  
# Importing the dataset 
#bike = datasets.load_bike()
#X, y = bike.data, bike.target
  
# Splitting dataset
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.11, random_state = SEED)
  
# Instantiate Gradient Boosting Regressor
gbr = GradientBoostingRegressor(n_estimators = 200, max_depth = 1, random_state = SEED)
  
# Fit to training set
gbr.fit(train_X, train_y)
  
# Predict on test set
pred_y = gbr.predict(test_X)
  
# test set RMSE
test_rmse = MSE(test_y, pred_y) ** (1 / 2)
  
# Print rmse
print('RMSE test set: {:.2f}'.format(test_rmse))

RMSE test set: 0.49

In [13]:
train_y

922     2.609
867     3.591
1049    3.887
1073    2.479
587     3.829
        ...
466     3.846
121     4.235
1044    4.212
1095    2.588
860     3.053
Name: MOS , Length: 993, dtype: float64

In [14]:
from sklearn.metrics import mean_squared_error
mean_squared_error(test_y,pred_y)

0.23558764768122575

In [15]:
import math
MSE = np.square(np.subtract(test_y,pred_y)).mean() 
 
RMSE = math.sqrt(MSE)
print("Root Mean Square Error:\n")
print(RMSE)

Root Mean Square Error:

0.4853737196029733

In [16]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(test_y,pred_y)

0.37636147255975355

In [17]:
from sklearn.metrics import mean_absolute_error
print("MAE",mean_absolute_error(test_y,pred_y))

MAE 0.37636147255975355

In [18]:
from sklearn.metrics import r2_score
r2 = r2_score(test_y,pred_y)
print(r2) #this says this model R2 score is between zero and one like 0.8 which means your model is capable to explain 80 per cent of the variance of data

0.43049862758910096

In [19]:
import pandas as pd
from scipy.stats import pearsonr
corr,_=pearsonr(test_y,pred_y)
print('Pearsons correlation: %.3f' % corr)

Pearsons correlation: 0.670

In [20]:
import scipy.stats
def spearmans_rank_correlation(x, y):
     
    # Calculate the rank of x's
    xranks = pd.Series(x).rank()
    print("Rankings of X:")
    print(xranks)
     
    # Calculate the ranking of the y's
    yranks = pd.Series(y).rank()
    print("Rankings of Y:")
    print(yranks)
     
    # Calculate Pearson's correlation coefficient on the ranked versions of the data
    print("Spearman's Rank correlation:",scipy.stats.pearsonr(xranks, yranks)[0])
 
# Call the function
spearmans_rank_correlation(test_y,pred_y)

Rankings of X:
993     71.0
101      3.0
486     80.0
862     95.0
1075    13.0
        ...
1085    53.0
23       4.0
721     68.0
367     62.0
541     96.0
Name: MOS , Length: 123, dtype: float64
Rankings of Y:
0       79.0
1        1.0
2      107.5
3       51.0
4       30.5
       ...
118     48.0
119     17.0
120     63.0
121     37.0
122     96.0
Length: 123, dtype: float64
Spearman's Rank correlation: 0.694922714572508

In [21]:
from scipy.stats import kendalltau
corr, _ = kendalltau(test_y,pred_y)
print('Kendall Rank correlation: %.5f' % corr)

Kendall Rank correlation: 0.50734